dist: xenial
language: java
go:
  - 1.11.x
jdk:
  - openjdk8
node_js:
  - 9.11.2
services:
  - docker
cache:
  directories:
    - .autoconf
    - $HOME/.m2
before_install:
  - npm i -g npm
  - mkdir -p $HOME/gopath/src/github.com/cellery-io
  - mv ${TRAVIS_BUILD_DIR} $GOPATH/src/github.com/cellery-io/cellery-hub
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/cellery-io/cellery-hub
  - cd $HOME/gopath/src/github.com/cellery-io/cellery-hub
script:
  - make clean init check-style build test docker
after_success:
  - bash <(curl -s https://codecov.io/bash)
