[security]
certfile="/security/api-tls.crt"
keyfile="/security/api-tls.pem"
truststore="/security/truststore.p12"
truststorepass="ballerina"

[idp.oidc]
clientid="celleryhubapplication"
clientsecret="celleryhubapplication"

[portal]
publicurl="https://hub.cellery.io:9000"

[database]
host="mysql.hub.internal"
port=3306
default="CELLERY_HUB"
user="celleryhub"
password="celleryhub"

[filter.captcha]
secret="someSecret"
endpoint="https://www.google.com/recaptcha/api/siteverify"
engaged.paths="[{\"path\" : \"/api/0.1.0/orgs/*\", \"method\": \"post\"}]"
max.allowd.organization.count=3

[idp]
endpoint="https://idp.hub.cellery.io:9443"
token.endpoint="/oauth2/token"
introspection.endpoint="/oauth2/introspect"
scim2.user.endpoint="/scim2/Users"
username="admin"
password="admin"

[token]
cache.expiry=1800000
cache.capacity=500

[b7a.log]
level="DEBUG"

[b7a.sql]
connection.auto.commit=true
max.pool.size=100
